# .github/workflows/ci.yml
name: CI

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel

          # 1) Make pytest available
          pip install pytest

          # 2) Preload a binary wheel for blis (avoids any source build)
          pip install blis==0.7.9

          # 3) Install the rest, preferring wheels
          pip install --prefer-binary -r requirements.txt

          # 4) Finally, pull in the spaCy model wheel
          pip install https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.7.1/en_core_web_sm-3.7.1-py3-none-any.whl

      - name: Run tests
        shell: bash
        run: |
          # allow “no tests collected” (exit 5) without failing the job
          set +e
          python -m pytest -q
          status=$?
          if [ $status -ne 0 ] && [ $status -ne 5 ]; then
            exit $status
          fi

      - name: Show Streamlit version
        run: streamlit --version