name: CI

on:
  # Run on pushes or pull‑requests targeting the main branch only
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]
  # Allow manual triggering from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest  # GitHub‑hosted Ubuntu runner

    steps:
      - uses: actions/checkout@v3           # 1️⃣  Check out repository code

      - uses: actions/setup-python@v4       # 2️⃣  Install Python 3.9 on the runner
        with:
          python-version: '3.9'

      - name: Install dependencies          # 3️⃣  Create venv & install requirements
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt
          python -m spacy download en_core_web_sm

      - name: Run tests                     # 4️⃣  Execute pytest test suite
        run: |
          source .venv/bin/activate
          pytest

      - name: Verify Streamlit installation # 5️⃣  Show Streamlit version as a sanity check
        run: |
          source .venv/bin/activate
          streamlit --version
