# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          # pre-install a binary wheel for blis so spaCy doesn't pull in a tar.gz
          pip install blis==0.7.9
          # now install everything else, forcing wheels when available
          pip install --prefer-binary -r requirements.txt
          # finally pull in the spaCy model
          pip install \
            https://github.com/explosion/spacy-models/releases/download/\en_core_web_sm-3.7.1/en_core_web_sm-3.7.1-py3-none-any.whl

      - name: Run tests
        run: python -m pytest -q

      - name: Show Streamlit version
        run: streamlit --version