# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Cache pip downloads
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Build wheelhouse
        run: |
          python -m pip install --upgrade pip
          mkdir -p wheelhouse
          # Download wheels (or sdist) for every requirement; blis will be a wheel
          pip download -r requirements.txt -d wheelhouse

      - name: Install dependencies from wheelhouse
        run: |
          # Install purely from our local wheelhouse
          python -m pip install --no-index --find-links=wheelhouse -r requirements.txt
          # Then pull in the spaCy model wheel too
          python -m pip install \
            --no-index \
            --find-links=wheelhouse \
            https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.7.1/en_core_web_sm-3.7.1-py3-none-any.whl

      - name: Run tests
        run: python -m pytest -q

      - name: Show Streamlit version
        run: streamlit --version